### ISSUE TITLE
VRNetzer DB seems to be broken

### ISSUE THREAD

**Issue by sepppirch** [menchelab/Analytics_Module#22]
\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'Datadivr_meta.namespaces' doesn't exist")

**Comment by sepppirch** [comment]
copy db from gibson when ready....

**Comment by Feliksmueller** [comment]
> \err.py", line 109, in raise_mysql_exception
> raise errorclass(errno, errval)
> pymysql.err.ProgrammingError: (1146, "Table 'Datadivr_meta.namespaces' doesn't exist")

What process looks for this table? There should be none...

**Comment by sepppirch** [comment]
The one that gets the projects
